<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <None Include="../package-icon.png" Pack="true" PackagePath="" Link="package-icon.png" />
    <None Include="../../README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TALXIS.CLI.Features.Data\TALXIS.CLI.Features.Data.csproj" />
    <ProjectReference Include="..\TALXIS.CLI.Features.Environment\TALXIS.CLI.Features.Environment.csproj" />
    <ProjectReference Include="..\TALXIS.CLI.Features.Docs\TALXIS.CLI.Features.Docs.csproj" />
    <ProjectReference Include="..\TALXIS.CLI.Logging\TALXIS.CLI.Logging.csproj" />
    <ProjectReference Include="..\TALXIS.CLI.Features.Workspace\TALXIS.CLI.Features.Workspace.csproj" />
    <ProjectReference Include="..\TALXIS.CLI.Core\TALXIS.CLI.Core.csproj" />
    <ProjectReference Include="..\TALXIS.CLI.Features.Config\TALXIS.CLI.Features.Config.csproj" />
    <ProjectReference Include="..\TALXIS.CLI.Platform.Dataverse.Runtime\TALXIS.CLI.Platform.Dataverse.Runtime.csproj" />
    <ProjectReference Include="..\TALXIS.CLI.Platform.Dataverse.Application\TALXIS.CLI.Platform.Dataverse.Application.csproj" />
    <ProjectReference Include="..\TALXIS.CLI.Features.Security\TALXIS.CLI.Features.Security.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotMake.CommandLine" Version="2.6.7" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- NuGet packaging and tool-specific metadata -->
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>txc</ToolCommandName>
    <PackageId>TALXIS.CLI</PackageId>
    <Title>TALXIS CLI (txc)</Title>
    <Authors>NETWORG</Authors>
    <Product>TALXIS CLI</Product>
    <Description>TALXIS CLI (txc) is a .NET global tool for developer automation and Power Platform scripting.</Description>
    <PackageTags>cli;dotnet-tool;talxis;automation;powerplatform;txc</PackageTags>
    <PackageProjectUrl>https://github.com/TALXIS/tools-cli</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>package-icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Copyright>© 2025 NETWORG Corporation - MIT License</Copyright>
  </PropertyGroup>

</Project>
